error_message: cannot assign slice from input of different size
error_traceback: "  File \"/home/darlinne.soto/new_framework/ray-tune-search/execute_once_one_experiment.py\"\
  , line 16, in execute_once\n    result = h_search_unit(\n\n  File \"/home/darlinne.soto/new_framework/ray-tune-search/h_search_unit.py\"\
  , line 23, in h_search_unit\n    experiment_result = run_basic_experiment(\n\n \
  \ File \"/home/darlinne.soto/new_framework/ray-tune-search/basic/run_basic_experiment.py\"\
  , line 156, in run_basic_experiment\n    datasets = do_reduce(\n\n  File \"/home/darlinne.soto/new_framework/ray-tune-search/basic/do_reduce.py\"\
  , line 121, in do_reduce\n    reducer.fit(**fit_dsets)\n\n  File \"/usr/local/lib/python3.10/site-packages/umap/umap_.py\"\
  , line 2608, in fit\n    ) = nearest_neighbors(\n\n  File \"/usr/local/lib/python3.10/site-packages/umap/umap_.py\"\
  , line 329, in nearest_neighbors\n    knn_search_index = NNDescent(\n\n  File \"\
  /usr/local/lib/python3.10/site-packages/pynndescent/pynndescent_.py\", line 804,\
  \ in __init__\n    leaf_array = rptree_leaf_array(self._rp_forest)\n\n  File \"\
  /usr/local/lib/python3.10/site-packages/pynndescent/rp_trees.py\", line 1097, in\
  \ rptree_leaf_array\n    return np.vstack(rptree_leaf_array_parallel(rp_forest))\n\
  \n  File \"/usr/local/lib/python3.10/site-packages/pynndescent/rp_trees.py\", line\
  \ 1089, in rptree_leaf_array_parallel\n    result = joblib.Parallel(n_jobs=-1, require=\"\
  sharedmem\")(\n\n  File \"/usr/local/lib/python3.10/site-packages/joblib/parallel.py\"\
  , line 1952, in __call__\n    return output if self.return_generator else list(output)\n\
  \n  File \"/usr/local/lib/python3.10/site-packages/joblib/parallel.py\", line 1595,\
  \ in _get_outputs\n    yield from self._retrieve()\n\n  File \"/usr/local/lib/python3.10/site-packages/joblib/parallel.py\"\
  , line 1699, in _retrieve\n    self._raise_error_fast()\n\n  File \"/usr/local/lib/python3.10/site-packages/joblib/parallel.py\"\
  , line 1734, in _raise_error_fast\n    error_job.get_result(self.timeout)\n\n  File\
  \ \"/usr/local/lib/python3.10/site-packages/joblib/parallel.py\", line 736, in get_result\n\
  \    return self._return_or_raise()\n\n  File \"/usr/local/lib/python3.10/site-packages/joblib/parallel.py\"\
  , line 754, in _return_or_raise\n    raise self._result\n"
error_type: <class 'ValueError'>
num_params: -1.0
num_trainable_params: -1.0
score: -0.1
